# Generated by Django 5.2.7 on 2025-10-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0002_alter_plantilladocumento_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquetas_dinamicas', models.JSONField(blank=True, default=dict, help_text='Diccionario con etiquetas dinamicas definidas por el usuario', verbose_name='Campos adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('llave_maestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='Core.registrocalificado', to_field='llave_documento')),
            ],
        ),
    ]
