# Generated by Django 5.2.7 on 2025-10-16 01:21

import app.Core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Renovación', 'Renovación'), ('Modificación', 'Modificación')], max_length=20)),
                ('archivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/plantillas/', location='D:\\Repositorio\\Cun\\registro-calificado-api\\app\\Core\\data'), upload_to=app.Core.models.plantilla_repo_path)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCalificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave_documento', models.CharField(max_length=300, unique=True, verbose_name='Llave del documento')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de documento')),
                ('snies', models.CharField(max_length=50, unique=True, verbose_name='SNIES')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
