# Generated by Django 5.2.7 on 2025-10-16 01:48

import app.Core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilladocumento',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/plantillas/', location='/app/app/Core/data'), upload_to=app.Core.models.plantilla_repo_path),
        ),
    ]
