# Generated by Django 5.2.7 on 2025-10-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_plantilladocumento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocalificado',
            name='snies',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SNIES'),
        ),
    ]
